logging:
  level:
    root: INFO
spring:
  broker:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual
    publisher-confirm-type: correlated
    publisher-returns: true
    queues:
      manager:
        name: managerQueue
        routing-key: manager
        exchange: myexchange
      worker:
        name: workerQueue
        routing-key: worker
        exchange: myexchange
    own-queue: ${QUEUE}