spring:
  rabbitmq:
    host: rabbitmq
    username: guest
    password: guest
    virtual-host: /
    queues:
      manager:
        name: managerQueue
        routing-key: manager
        exchange: myexchange
      workers:
        - name: workerQueue1
          routing-key: worker1
          exchange: myexchange
        - name: workerQueue2
          routing-key: worker2
          exchange: myexchange
    own-queue: ${QUEUE}